### ISSUE TITLE
Training yaml

### ISSUE THREAD

**Issue by chengstark** [batmanlab/Mammo-CLIP#1]
Hello! Thank you for publishing the code!
I'm wondering if you could clarify which YAML file was used to train the CLIP model (efficient net 5b + Bio_ClinicalBERT)?

**Comment by shantanu-ai** [comment]
This one: [pre_train_b5_clip.yaml](https://github.com/batmanlab/Mammo-CLIP/blob/main/src/codebase/configs/pre_train_b5_clip.yaml)

All the corresponding yaml files are referred from here based on hydra

**Comment by chengstark** [comment]
Thanks for the quick response! 
Which CSV file contains the REPORT column? After reading the code this seems to be the text encoder input column, please correct me if I am wrong.

**Comment by shantanu-ai** [comment]
Here is my answer:
For data preparation you should go to this [part](https://github.com/batmanlab/Mammo-CLIP/tree/main?tab=readme-ov-file#data-preparation-for-pretraining) 

We have given a demo csv [upmc_dicom_consolidated_final_folds_BIRADS_num_1_report.csv](https://github.com/batmanlab/Mammo-CLIP/blob/main/src/codebase/data_csv/upmc_dicom_consolidated_final_folds_BIRADS_num_1_report.csv). You should have either of findings and impressions or both. Once you have this csv, call this function: [augment_text.py](https://github.com/batmanlab/Mammo-CLIP/blob/main/src/codebase/augment_text.py) with the csv and it will give you the final csv:  [clip_pretrain_100.csv](https://github.com/batmanlab/Mammo-CLIP/blob/main/src/codebase/data_csv/clip_pretrain_100.csv). This final csv file will be used for pretraining.

During pre-training, text encoder of Mammo-CLIP needs `text` and `text_augment` columns as specified in this file: [clip_pretrain_100.csv](https://github.com/batmanlab/Mammo-CLIP/blob/main/src/codebase/data_csv/clip_pretrain_100.csv).

**Comment by chengstark** [comment]
Got it, thank you!
