### ISSUE TITLE
Augmentation for the images

### ISSUE THREAD

**Issue by emrekeles-arch** [batmanlab/Mammo-CLIP#12]
@shantanu-ai 
Hello, it's me again
I wonder if you applied any augmentation technique for the images ?
I couldn't find any function for data augmentation.

Thank you

**Comment by shantanu-ai** [comment]
@emrekeles-arch 

* For pretraining, this [link](https://github.com/batmanlab/Mammo-CLIP/blob/main/src/codebase/breastclip/data/data_utils.py)

* For downstream, this [link](https://github.com/batmanlab/Mammo-CLIP/blob/main/src/codebase/breastclip/data/data_utils.py)
