### ISSUE TITLE
Augmentations for Mammo-CLIP

### ISSUE THREAD

**Issue by Smith6791** [batmanlab/Mammo-CLIP#14]
Hi,
Great work. Can u please specify the specific augmentations u use for pre-training/classification/detection? Also i read this paper: Ladder (https://arxiv.org/pdf/2408.07832). Do you use the same Mammo-CLIP to probe the failure modes in ladder as well? Or there is any difference? Bcz there is no code for Ladder repo. I believe you are the same author for both the papers.

**Comment by shantanu-ai** [comment]
Hi @Smith6791 
* for preraining, follow [this](https://github.com/batmanlab/Mammo-CLIP/blob/main/src/codebase/breastclip/data/data_utils.py)
* for classification/detection, follow [this](https://github.com/batmanlab/Mammo-CLIP/blob/main/src/codebase/Datasets/dataset_utils.py)

Also, for detection, use the CSV file specified in the readme as we have resized the images, so we reshaped the bounding boxes accordingly.

For your query on ladder, yes we are the same group who created ladder. We are doing more comprehensive evaluations for ladder, so the draft in arxiv will be edited soon. Ladder uses Mammo-CLIP to probe the classifier to discover the error slices. Also keep an eye of the repo of ladder as the code will also be uploaded soon there.

**Comment by Smith6791** [comment]
Hi, 
Thanks for reply. Can u plz give me the folder structure of the datasets u used?

**Comment by shantanu-ai** [comment]
Hi @Smith6791 
Look into [this](https://github.com/batmanlab/Mammo-CLIP?tab=readme-ov-file#final-dataset-directory-structures)
