### ISSUE TITLE
Image encoders besides EfficientNets for downstream classification tasks 

### ISSUE THREAD

**Issue by marianamourao-37** [batmanlab/Mammo-CLIP#16]
Hello :) 

Congrats on the work developed!

I am interested in using pre-trained image encoders for downstream classification tasks. As I understand it, the available checkpoints are for EfficientNets. If I wanted to consider ResNets or Swin Transformer, would I need to first pre-train Mammo-CLIP with these image encoders using the train.py script?

Thanks in advance!

**Comment by shantanu-ai** [comment]
Hi @marianamourao-37, 
Thanks for taking interest in our paper. So, with the pre-trained weights, u get the pre-trained Efficientnet-B5 and B2 image encoders, respectively. If u want resnet or Swin transformer, you have to pre-train it from scratch with your data based on the readme.md file from our repo.
Thanks

**Comment by marianamourao-37** [comment]
Thanks for the quick reply. 

Pre-train from scratch with my data means that it will not take into account the private dataset used in your work?

**Comment by shantanu-ai** [comment]
yes.
