### ISSUE TITLE
Pretraining Mammo-CLIP Code running error, missing necessary file

### ISSUE THREAD

**Issue by xiang-zhibo** [batmanlab/Mammo-CLIP#17]
An error occurred when running the command python./ src/codebase/train.py --config-name pre_train_b5_clip.yaml.
Some files are missing from the training section of the uploaded code, such as train_fast, and other similar files.Please ask if the code you uploaded is up to date and working properly

**Comment by shantanu-ai** [comment]
Can u please paste the error?
I believe all the files are uploaded properly.

**Comment by xiang-zhibo** [comment]
The train_fast package is unused, and it can run normally after comments are removed. There is no problem with the code. Thank you for your work.

**Comment by xiang-zhibo** [comment]
The train_fast package is not used. After commenting out the relevant code, it can run normally without any problems. Thank you for your work.

跟读

**Comment by shantanu-ai** [comment]
Yes. I fixed the bug just now. Thank you for pointing that out
