### ISSUE TITLE
Mismatched Embedding Dimensions for Image and Text in MammoCLIP

### ISSUE THREAD

**Issue by GuilhermeJC13** [batmanlab/Mammo-CLIP#21]
Hello,

I am working on calculating cosine similarity between an image and a report using MammoCLIP. In typical CLIP models, both the image and text encoders output embeddings with the same dimensions, making direct similarity calculations straightforward. However, with MammoCLIP, I’ve encountered a dimensional mismatch:

1. Text embedding dimension: 768
2. Image embedding dimension: 2048

Is this dimensional difference expected in MammoCLIP? Do you use a projection layer or any other method to resize embeddings to a compatible dimension? If so, I’d appreciate any guidance on implementing this or any existing scripts for calculating cosine similarity given this setup.

Thank you for your assistance!

**Comment by shantanu-ai** [comment]
@GuilhermeJC13 
Please look into the forward method of [clip.py](https://github.com/batmanlab/Mammo-CLIP/blob/main/src/codebase/breastclip/model/clip.py) -- line 86-91. We first got the embedding and then pass it through the projection layers. 2048 is the image embedding dimension before the projection.

**Comment by GuilhermeJC13** [comment]
Great, this is what I was looking for.

Thanks a lot!
