### ISSUE TITLE
detection downstream task checkpoints

### ISSUE THREAD

**Issue by hyeondongChoi** [batmanlab/Mammo-CLIP#23]
Hi,
Thank you so much for your great work and for publishing this project.

I was able to perform the evaluation for the classification downstream task, but I couldn't perform the evaluation for the detection downstream task. The reason is that I couldn't find the checkpoint weights file for the detection task. The folder appears to be empty.

I downloaded the checkpoint weights from the following link: 
https://huggingface.co/shawn24/Mammo-CLIP/tree/main/Downstream-checkpoints.

Could you please let me know where I can get the checkpoints for the detection downstream task?

**Comment by shantanu-ai** [comment]
@hyeondongChoi 

Apologies. U can find the detection checkpoints [here](https://huggingface.co/shawn24/Mammo-CLIP/blob/main/Downstream-checkpoints/Mammo-CLIP-Detection.zip). I name the folders accordingly matching the finding name and whether its linear probe or full fine-tune.
