### ISSUE TITLE
Reported detection results

### ISSUE THREAD

**Issue by karimelbarbary16** [batmanlab/Mammo-CLIP#24]
Hello,

Thank you for your excellent work. I have a question regarding the detection part: You fine-tuned two separate models for the two classes (Mass and Calcification) that you are detecting and the reported results are based on testing each model on its respective class, correct?

**Comment by shantanu-ai** [comment]
Yes, we did not perform multi-class detection as there is a big variability in the data. We performed detection/classification for each class.
