### ISSUE TITLE
Enhancing data quality

### ISSUE THREAD

**Issue by emrekeles-arch** [batmanlab/Mammo-CLIP#26]
I hope you're doing well. I’ve returned after a long break and have a question :) . Could you kindly share which pre/post-processing methods you have applied to improve the quality of mammogram images?

Thank you very much.

**Comment by shantanu-ai** [comment]
Hi @emrekeles-arch,
We did not do any special pre/post process to improve the quality of the mammograms. We follow the script from kaggle competition.  All preprocessing steps are included in the readme.md. You can start from [here](https://github.com/batmanlab/Mammo-CLIP?tab=readme-ov-file#pre-processing-images)
