### ISSUE TITLE
vinDR dataset

### ISSUE THREAD

**Issue by emrekeles-arch** [batmanlab/Mammo-CLIP#4]
Do you have a processed version of the vindr dataset? Since I am working on Colab, I do not have enough disk space to download and extract, so I cannot use this data set. I also took a look at the vindr dataset with png extension on Kaggle, but the images do not match the information in the csv file. If you have it and it won't cause any problems, can you share it via a drive link ?

**Comment by shantanu-ai** [comment]
Did you try our preprocessing steps for VinDr. U just need to download the files from official directory and preprocess it with the steps mentioned in the readme?

**Comment by emrekeles-arch** [comment]
The zipped version of the vindr data set is 50 GB, but when you unzip it, it becomes 340 GB. The disk space provided by Colab is limited to 100, so it is not possible to perform operations? Also, I don't have that much free space on my local computer? If it is not difficult for you to share, it would be very useful for me. If it is a difficult process, I will find an alternative way.

**Comment by shantanu-ai** [comment]
@emrekeles-arch , all the vindr png images are uploaded [here](https://www.kaggle.com/datasets/shantanughosh/vindr-mammogram-dataset-dicom-to-png).

**Comment by emrekeles-arch** [comment]
@shantanu-ai, I can't thank you enough, i am grateful.
