### ISSUE TITLE
code for generating feature maps by Mammo-FActOR

### ISSUE THREAD

**Issue by lemonwjn235** [batmanlab/Mammo-CLIP#7]
Hi,

I have read the paper and code. I am interested in generating feature maps by Mammo-FActOR. Do you have the code of this part?

**Comment by shantanu-ai** [comment]
Yes. we are still in progress to upload the code for Mammo-Factor.

**Comment by shantanu-ai** [comment]
@lemonwjn235, for Mammo-FActOR, refer to the following [notebook](https://github.com/batmanlab/Mammo-CLIP/blob/main/src/codebase/notebooks/Mammo-Factor/Mammo-Factor.ipynb).
