### ISSUE TITLE
Missing Config File

### ISSUE THREAD

**Issue by yan297** [batmanlab/Mammo-CLIP#9]
Hi, thank you for your work! 

when I was trying to run the eval_zero_shot_clip.py for the Zero-shot evaluation. I encountered the following error. Could you kindly help me with that? 

Error executing job with overrides: ['model.clip_check_point=./src/codebase/outputs/upmc_clip/b2_detector_period_n/checkpoints/fold_0/b2-model-best-epoch-10.tar']
Traceback (most recent call last):
  File "/home/zyan297/anaconda3/envs/Mammo-CLIP/lib/python3.8/site-packages/huggingface_hub/utils/_errors.py", line 304, in hf_raise_for_status
    response.raise_for_status()
  File "/home/zyan297/anaconda3/envs/Mammo-CLIP/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: https://huggingface.co/emilyalsentzer/Bio_ClinicalBERT/resolve/main/tokenizer_config.json

Thank you.

**Comment by shantanu-ai** [comment]
I think this error is due to a problem while downloading the Bio_clinicalBERT from huggingface. Can you please check if BioclinicalBERT is downloaded successfully in your .config directory. Also u can manually download or redirect the download using the following coder:
```python
from transformers import AutoTokenizer, AutoModel

# Download the files manually and place them in the correct directory
tokenizer = AutoTokenizer.from_pretrained('./local_path_to_tokenizer')
model = AutoModel.from_pretrained('./local_path_to_model')

```

**Comment by yan297** [comment]
Thank you for your quick reply! 

I have checked the URL, but the main branch has already been modified to https://huggingface.co/emilyalsentzer/Bio_ClinicalBERT/tree/main. I can't find the original tokenizer_config.json file.

**Comment by shantanu-ai** [comment]
Can you please check if set this path correctly: [here](https://github.com/batmanlab/Mammo-CLIP/blob/6883341655e7845ed7cc9f490f5886e44acf0b15/src/codebase/breastclip/data/data_utils.py#L10)

Also, can u plz tell me if your installed versions are same as the our environment.yml file?

**Comment by shantanu-ai** [comment]
@yan297 
We set the path [here](https://github.com/batmanlab/Mammo-CLIP/blob/6883341655e7845ed7cc9f490f5886e44acf0b15/src/codebase/configs/tokenizer/clinical_bert.yaml)

```
cache_dir: "${base.data_dir}/Mammo-CLIP/src/codebase/outputs/huggingface/tokenizers"
```

**Comment by yan297** [comment]
Yes, the codes are totally the same and I followed your steps and used your environment.yml file to create a conda env. 

The author of emilyalsentzer/Bio_ClinicalBERT has removed that file: (resolve/main/tokenizer_config.json).

**Comment by shantanu-ai** [comment]
@yan297
This is the huggingface file i used [file](https://huggingface.co/shawn24/Mammo-CLIP/blob/main/huggingface.zip)
Can u plz download and see?

**Comment by yan297** [comment]
Got it! Thank you for your positive response! I appreciate it.
